// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// linCmtDeltaMemo
int linCmtDeltaMemo(int on);
RcppExport SEXP _rxode2lincmt_linCmtDeltaMemo(SEXP onSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type on(onSEXP);
    rcpp_result_gen = Rcpp::wrap(linCmtDeltaMemo(on));
    return rcpp_result_gen;
END_RCPP
}
// linCmtSeqStats
IntegerVector linCmtSeqStats(bool reset);
RcppExport SEXP _rxode2lincmt_linCmtSeqStats(SEXP resetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type reset(resetSEXP);
    rcpp_result_gen = Rcpp::wrap(linCmtSeqStats(reset));
    return rcpp_result_gen;
END_RCPP
}
// linCmtModelDouble
RObject linCmtModelDouble(double dt, double p1, double v1, double p2, double p3, double p4, double p5, double ka, NumericVector alastNV, NumericVector rateNV, const int ncmt, const int oral0, const int trans, bool deriv, int type, double tau, double tinf, double amt, int bolusCmt, int ndiff, int sensType, double sensH);
RcppExport SEXP _rxode2lincmt_linCmtModelDouble(SEXP dtSEXP, SEXP p1SEXP, SEXP v1SEXP, SEXP p2SEXP, SEXP p3SEXP, SEXP p4SEXP, SEXP p5SEXP, SEXP kaSEXP, SEXP alastNVSEXP, SEXP rateNVSEXP, SEXP ncmtSEXP, SEXP oral0SEXP, SEXP transSEXP, SEXP derivSEXP, SEXP typeSEXP, SEXP tauSEXP, SEXP tinfSEXP, SEXP amtSEXP, SEXP bolusCmtSEXP, SEXP ndiffSEXP, SEXP sensTypeSEXP, SEXP sensHSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< double >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< double >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< double >::type p3(p3SEXP);
    Rcpp::traits::input_parameter< double >::type p4(p4SEXP);
    Rcpp::traits::input_parameter< double >::type p5(p5SEXP);
    Rcpp::traits::input_parameter< double >::type ka(kaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alastNV(alastNVSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rateNV(rateNVSEXP);
    Rcpp::traits::input_parameter< const int >::type ncmt(ncmtSEXP);
    Rcpp::traits::input_parameter< const int >::type oral0(oral0SEXP);
    Rcpp::traits::input_parameter< const int >::type trans(transSEXP);
    Rcpp::traits::input_parameter< bool >::type deriv(derivSEXP);
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type tinf(tinfSEXP);
    Rcpp::traits::input_parameter< double >::type amt(amtSEXP);
    Rcpp::traits::input_parameter< int >::type bolusCmt(bolusCmtSEXP);
    Rcpp::traits::input_parameter< int >::type ndiff(ndiffSEXP);
    Rcpp::traits::input_parameter< int >::type sensType(sensTypeSEXP);
    Rcpp::traits::input_parameter< double >::type sensH(sensHSEXP);
    rcpp_result_gen = Rcpp::wrap(linCmtModelDouble(dt, p1, v1, p2, p3, p4, p5, ka, alastNV, rateNV, ncmt, oral0, trans, deriv, type, tau, tinf, amt, bolusCmt, ndiff, sensType, sensH));
    return rcpp_result_gen;
END_RCPP
}
// linCmtCarrySetFast
LogicalVector linCmtCarrySetFast(bool enable);
RcppExport SEXP _rxode2lincmt_linCmtCarrySetFast(SEXP enableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type enable(enableSEXP);
    rcpp_result_gen = Rcpp::wrap(linCmtCarrySetFast(enable));
    return rcpp_result_gen;
END_RCPP
}
// linCmtCarrySentinelMax
IntegerVector linCmtCarrySentinelMax();
RcppExport SEXP _rxode2lincmt_linCmtCarrySentinelMax() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(linCmtCarrySentinelMax());
    return rcpp_result_gen;
END_RCPP
}
// linCmtCarryFastStats
NumericVector linCmtCarryFastStats(bool reset);
RcppExport SEXP _rxode2lincmt_linCmtCarryFastStats(SEXP resetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type reset(resetSEXP);
    rcpp_result_gen = Rcpp::wrap(linCmtCarryFastStats(reset));
    return rcpp_result_gen;
END_RCPP
}
// linCmtCarryLiveTest
NumericVector linCmtCarryLiveTest(int id, NumericVector t, NumericVector tPrior, NumericMatrix theta, int ncmt, int oral0, int trans, IntegerVector which1, IntegerVector which2, Nullable<NumericVector> addVal);
RcppExport SEXP _rxode2lincmt_linCmtCarryLiveTest(SEXP idSEXP, SEXP tSEXP, SEXP tPriorSEXP, SEXP thetaSEXP, SEXP ncmtSEXP, SEXP oral0SEXP, SEXP transSEXP, SEXP which1SEXP, SEXP which2SEXP, SEXP addValSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type id(idSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tPrior(tPriorSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type ncmt(ncmtSEXP);
    Rcpp::traits::input_parameter< int >::type oral0(oral0SEXP);
    Rcpp::traits::input_parameter< int >::type trans(transSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type which1(which1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type which2(which2SEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type addVal(addValSEXP);
    rcpp_result_gen = Rcpp::wrap(linCmtCarryLiveTest(id, t, tPrior, theta, ncmt, oral0, trans, which1, which2, addVal));
    return rcpp_result_gen;
END_RCPP
}
// linCmtBSensTypesSeen
IntegerVector linCmtBSensTypesSeen(bool reset);
RcppExport SEXP _rxode2lincmt_linCmtBSensTypesSeen(SEXP resetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type reset(resetSEXP);
    rcpp_result_gen = Rcpp::wrap(linCmtBSensTypesSeen(reset));
    return rcpp_result_gen;
END_RCPP
}
// linCmtBThreadsSeen
int linCmtBThreadsSeen(bool reset);
RcppExport SEXP _rxode2lincmt_linCmtBThreadsSeen(SEXP resetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type reset(resetSEXP);
    rcpp_result_gen = Rcpp::wrap(linCmtBThreadsSeen(reset));
    return rcpp_result_gen;
END_RCPP
}
