# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Force the delta-keyed exponential memo on or off (tests/benchmarks)
#'
#' @param on integer: 1 forces the memo on, 0 forces it off, -1 (the
#'   default) follows the RX_LINCMT_DELTA_MEMO environment latch read at
#'   window-fill time
#' @return the previous setting, invisibly usable to restore it
#' @keywords internal
#' @export
.linCmtDeltaMemo <- function(on = -1L) {
    .Call(`_rxode2lincmt_linCmtDeltaMemo`, on)
}

#' Read (and optionally reset) the amortized linCmt() sequential counters
#'
#' @param reset logical; when TRUE zero the counters after reading
#' @return named integer vector: windows (window-constant recomputations),
#'   seqTailRows (rows evaluated from the window's dt-dependent tail),
#'   seqFullRows (rows that fell back to the full forward evaluator),
#'   valueCompute (value executions that solved the row),
#'   valueRestore (value executions that restored an already-solved row),
#'   memoHit (value executions short-circuited by the last-row memo),
#'   valueLite (already-solved value re-executions served by the thin
#'   fx-plus-scaling path with the Jacobian restore skipped),
#'   expBuild (delta-keyed exponential-memo builds: one per distinct row
#'   gap per theta window), expHit (rows whose exponentials came from the
#'   delta memo; disable with RX_LINCMT_DELTA_MEMO=off), expSolo (of
#'   those builds, the ones that went to the within-row slot the guard
#'   keeps serving after it stops speculating), dualRows (rows
#'   whose tail took one multi-direction pass, linCmtSensType="ADm"),
#'   phiAnalyticRows (rows propagated through the closed-form transition
#'   matrix; RX_LINCMT_PHI=2)
#' @keywords internal
#' @export
.linCmtSeqStats <- function(reset = FALSE) {
    .Call(`_rxode2lincmt_linCmtSeqStats`, reset)
}

#' Advance a linear compartment model by one step
#'
#' Advances the amounts of a one, two or three compartment linear model by
#' `dt` and returns the central concentration, optionally with its
#' derivatives.  This is the per-row kernel behind rxode2's `linCmt()`.
#'
#' @param dt time step
#' @param p1,v1,p2,p3,p4,p5 parameters in the `trans` parameterization (see
#'   [linCmtMicros()])
#' @param ka absorption rate constant (used when `oral0` is 1)
#' @param alastNV amounts at the start of the step (depot first when
#'   `oral0` is 1, then central and peripherals); with `deriv = TRUE`
#'   followed by their parameter sensitivities
#' @param rateNV zero-order rates into each compartment, in the same order
#' @param ncmt number of compartments, 1 to 3
#' @param oral0 1 when the model has a depot compartment, otherwise 0
#' @param trans parameterization number
#' @param deriv logical; also return the derivatives
#' @param type 0 for a regular step; 1 and 2 steady-state infusion, 3
#'   steady-state bolus
#' @param tau steady-state dosing interval
#' @param tinf steady-state infusion duration
#' @param amt steady-state bolus amount
#' @param bolusCmt steady-state bolus compartment
#' @param ndiff differentiation bit mask as used by rxode2 (`ka` 1, `p1` 2,
#'   `v1` 4, `p2` 8, `p3` 16, `p4` 32, `p5` 64)
#' @param sensType derivative method: 3 or 30 forward-mode automatic
#'   differentiation, 32 all directions in one forward-mode pass, 31
#'   reverse mode, 100 automatic choice, 1 and 2 forward and central
#'   differences with the kernel's own step, 10 and 20 forward and central
#'   differences with step `sensH`
#' @param sensH finite-difference step for `sensType` 10 and 20
#' @return list with `val` (central concentration) and `Alast` (carried
#'   state after the step); with `deriv = TRUE` also `J` (Jacobian of the
#'   amounts) and `Jg` (gradient of `val`)
#' @export
#' @examples
#' linCmtModelDouble(1, 2, 20, 0, 0, 0, 0, 0, 100, 0, 1L, 0L, 1L, FALSE,
#'                   0L, 0, 0, 0, 0L, 0L)
linCmtModelDouble <- function(dt, p1, v1, p2, p3, p4, p5, ka, alastNV, rateNV, ncmt, oral0, trans, deriv, type, tau, tinf, amt, bolusCmt, ndiff, sensType = 3L, sensH = 0.001) {
    .Call(`_rxode2lincmt_linCmtModelDouble`, dt, p1, v1, p2, p3, p4, p5, ka, alastNV, rateNV, ncmt, oral0, trans, deriv, type, tau, tinf, amt, bolusCmt, ndiff, sensType, sensH)
}

#' Toggle the linCmt() carry-advance runtime fast path (test/benchmark hook)
#'
#' @param enable logical; new state
#' @return the previous state, invisibly
#' @keywords internal
#' @export
.linCmtCarrySetFast <- function(enable) {
    .Call(`_rxode2lincmt_linCmtCarrySetFast`, enable)
}

#' Highest carry sentinel `linCmtB(which1 = -k)` this build understands
#'
#' nlmixr2est gates its carry codegen on this: `-8` (the fast-path pin an
#' event-modifier jump needs) is only emitted when the loaded rxode2 has it.
#' @return integer, the magnitude of the most negative carry sentinel
#' @keywords internal
#' @export
.linCmtCarrySentinelMax <- function() {
    .Call(`_rxode2lincmt_linCmtCarrySentinelMax`)
}

#' Read (and optionally reset) the linCmt() carry-advance fast-path counters
#'
#' @param reset logical; when TRUE zero the counters after reading
#' @return named numeric vector: advCalls (every which1=-5 invocation),
#'   advFast (subset that took the constant-theta skip)
#' @keywords internal
#' @export
.linCmtCarryFastStats <- function(reset = FALSE) {
    .Call(`_rxode2lincmt_linCmtCarryFastStats`, reset)
}

#' Internal test/benchmark hook
#'
#' @noRd
#' @export
.linCmtCarryLiveTest <- function(id, t, tPrior, theta, ncmt, oral0, trans, which1, which2, addVal = NULL) {
    .Call(`_rxode2lincmt_linCmtCarryLiveTest`, id, t, tPrior, theta, ncmt, oral0, trans, which1, which2, addVal)
}

#' Internal test/benchmark hook
#'
#' @noRd
#' @export
.linCmtBSensTypesSeen <- function(reset) {
    .Call(`_rxode2lincmt_linCmtBSensTypesSeen`, reset)
}

#' Internal test/benchmark hook
#'
#' @noRd
#' @export
.linCmtBThreadsSeen <- function(reset) {
    .Call(`_rxode2lincmt_linCmtBThreadsSeen`, reset)
}

